/* Part 1: Create tables and insert data */
CREATE TABLE EMPLEADO (
ID INT,
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(59),
SEXO CHAR(1),
FECHA_NACIMIENTO DATE,
SALARIO DECIMAL(10,2)
);

CREATE TABLE VACACIONES(
ID INT,
ID_EMP INT,
FECHA_INICIO DATE,
FECHA_FIN DATE,
ESTADO CHAR(1),
CANTIDAD_DIAS INT
);

/*EN ESTA TABLA SE ALMACENA LA INFORMACIÓN BASICA DE LOS
EMPLEADOS*/
INSERT INTO EMPLEADO VALUES (1,'JUAN','PELAEZ','M','1985-01-29',3500000);
INSERT INTO EMPLEADO VALUES
(2,'ANDRES','GARCIA','M','1975-05-22',5500000);
INSERT INTO EMPLEADO VALUES (3,'LAURA','PEREZ','F','1991-09-10',2500000);
INSERT INTO EMPLEADO VALUES (4,'PEPE','MARTINEZ','M','1987-12-01',3800000);
INSERT INTO EMPLEADO VALUES (5,'MARGARITA','CORRALES','F','1990-07-02',4500000);

/*EN ESTA TABLA SE ALMACENA LAS SOLCITUDES DE VACACIONES DE CADA EMPLEADO*/
INSERT INTO VACACIONES VALUES
(1,1,'2019-07-01','2019-07-15','A',14);
INSERT INTO VACACIONES VALUES
(2,2,'2019-03-01','2019-03-15','R',14);
INSERT INTO VACACIONES VALUES
(3,2,'2019-04-01','2019-04-15','A',14);
INSERT INTO VACACIONES VALUES
(4,2,'2019-08-14','2019-08-20','A',6);
INSERT INTO VACACIONES VALUES
(5,3,'2019-08-20','2019-08-25','A',5);
INSERT INTO VACACIONES VALUES
(6,3,'2019-12-20','2019-12-31','A',11);

/* Part 2: Select NOMBRE, APELLIDO, SALARIO for all employees */
select NOMBRE, APELLIDO, SALARIO FROM EMPLEADO;

/* Part 3: Select NOMBRE, APELLIDO, SALARIO for all employees earning more than 4 million pesos */
select NOMBRE, APELLIDO, SALARIO
FROM EMPLEADO
WHERE SALARIO > 4000000;

/* Part 4: Count employees by sex */
SELECT SEXO, COUNT(SEXO) AS [CONTEO POR SEXO]
FROM EMPLEADO
GROUP BY SEXO;

/* Part 5: Select employees without any vacation request */
SELECT NOMBRE, APELLIDO
FROM EMPLEADO
WHERE ID NOT IN (SELECT DISTINCT ID_EMP FROM VACACIONES);

/* Part 6: Select employees with more than one vacation request and show the number of requests */
WITH CANTIDAD_VACACIONES AS (
 SELECT DISTINCT e.NOMBRE, e.APELLIDO, COUNT(v.ID_EMP) [CONTEO SOLICITUD VACACIONES]
  FROM VACACIONES v LEFT JOIN EMPLEADO e
  ON v.ID_EMP = e.ID
  GROUP BY e.NOMBRE, e.APELLIDO
)
SELECT *
FROM CANTIDAD_VACACIONES
WHERE [CONTEO SOLICITUD VACACIONES] > 1;

/* Part 7: Compute average salary of all employees */
SELECT AVG(SALARIO) [SALARIO PROMEDIO] FROM EMPLEADO;

/* Part 8: Compute the average CANTIDAD_DIAS per EMPLEADO */
SELECT DISTINCT e.NOMBRE, e.APELLIDO, AVG(CAST(v.CANTIDAD_DIAS AS NUMERIC)) [DIAS PROMEDIO VACACIONES]
  FROM VACACIONES v LEFT JOIN EMPLEADO e
  ON v.ID_EMP = e.ID
  GROUP BY e.NOMBRE, e.APELLIDO;

/* Part 9: Employee who has requested the most vacation days.
 * Displays name, surname, and total number of days requested.
 */
SELECT TOP 1 e.NOMBRE, e.APELLIDO, SUM(v.CANTIDAD_DIAS) [DIAS TOTALES VACACIONES]
  FROM VACACIONES v LEFT JOIN EMPLEADO e
  ON v.ID_EMP = e.ID
  GROUP BY e.NOMBRE, e.APELLIDO
  ORDER BY [DIAS TOTALES VACACIONES] DESC;

/* Auxiliar query to determine by-hand the average CANTIDAD_DIAS */
/*
SELECT e.NOMBRE, e.APELLIDO, v.CANTIDAD_DIAS
  FROM VACACIONES v LEFT JOIN EMPLEADO e
  ON v.ID_EMP = e.ID;
*/